os: linux
dist: xenial
language: node_js
node_js:
- 9.5.0

branches:
  except:
    - /^travis-.*-build$/

before_install:
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}

script:
  - npm install
  - npm run build
  - tar -C dist -cvzf ercole-web-${VERSION}.tar.gz .

before_deploy:
  - if [[ ${VERSION} == "latest" ]]; then git tag -f travis-${VERSION}-build; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote add gh https://simonerota:${GITHUB_RELEASE_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git; fi
  - if [[ ${VERSION} == "latest" ]]; then git push gh travis-${VERSION}-build || true; fi
  - if [[ ${VERSION} == "latest" ]]; then git push -f gh travis-${VERSION}-build; fi
  - if [[ ${VERSION} == "latest" ]]; then git remote remove gh; fi

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: ercole-web-*.tar.gz
  skip_cleanup: true
  name: $VERSION
  overwrite: true
  on:
    all_branches: true
