os: linux
dist: xenial
language: node_js
node_js:
- 9.5.0

addons:
  apt:
    packages:
      - rpm

env:
  global:
    - PACKAGE_BUILD_IMAGE=sorintdev/rpmbuild-centos7
    - WORKSPACE='/project'


before_install:
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}

install:
  - mkdir /tmp/dist
  - gem install --no-document fpm
  - npm install

script:
  - if [[ ${VERSION} == "latest" ]]; then sed -r 's/(ercole-agent((-virtualization)|(-setup))?)-(.*)((-1(.el[567])?.x86_64.rpm)|.exe)/\1-latest\6/' src/views/Agent.vue > /tmp/Agent.vue; fi
  - if [[ ${VERSION} == "latest" ]]; then cp /tmp/Agent.vue src/views/Agent.vue; fi
  - if [[ ${VERSION} == "latest" ]]; then sed -r 's/(Ercole )(.*)( &copy; 2018-19 Sorint.lab S.p.A.)/\1latest\3/' src/App.vue src/App.vue > /tmp/App.vue; fi
  - if [[ ${VERSION} == "latest" ]]; then cp /tmp/App.vue src/views/App.vue; fi
  - npm run build
  - tar -C dist -czf /tmp/dist/ercole-web-${VERSION}.tar.gz .
  - fpm -n ercole-web -s dir -t rpm -a all --rpm-os linux --version ${VERSION} --name ercole-web --after-install after-install -s dir dist/=/usr/share/ercole/web ercoleweb-setup=/usr/bin/ercoleweb-setup nginx-serve-ercoleweb-https.conf=/usr/share/ercole/examples/nginx-serve-ercoleweb-https.conf
  - mv ercole-web-${VERSION}-1.noarch.rpm /tmp/dist

deploy:
  - provider: script
    script: cd /tmp/dist/ && echo $MAGIC_SCRIPT | base64 -d | bash > /dev/stdout 2>/dev/stdout
    skip_cleanup: true
    file_glob: true
    file: dist/*
  - provider: releases
    api_key: $GITHUB_RELEASE_TOKEN
    file_glob: true
    file: /tmp/dist/*
    skip_cleanup: true
    name: $VERSION
    overwrite: true
    on:
      all_branches: true
      tags: true
